[template.environment]
  GQL_HOST = "https://aliexpress.andagna.com/graphql"
  NUXT_IMAGE_DOMAINS = "aliexpress.andagna.com,cheery-trifle-7cbacb.netlify.app"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://cheery-trifle-7cbacb.netlify.app/.*"]
